### ISSUE TITLE
The term 'Freeze' is incorrectly applied to mean 'Lock'

### ISSUE THREAD

**Issue by melwyncarlo** [LibreCAD/docs#102]
This is with regards to the **Dock Widgets** document (links below).

[GitHub Link](https://github.com/LibreCAD/docs/blob/master/ref/widgets.rst)
[LibreCAD Docs Link](https://librecad.readthedocs.io/en/latest/ref/widgets.html)

The term `Freeze` occurs only four times in the document _(can be accessed via `Ctrl+F`)_.

At all four occurrences, its use is incorrect. Either that, or the software code is.
As @lordofbikes mentioned in [LibreCAD Issue #1434](https://github.com/LibreCAD/LibreCAD/issues/1434), the term `Freeze` 
means the visibility of a layer, which is how it is interpreted in the software code. 
However, the docs relate that term with layer `Lock`. This is misleading.

Thank you very much. :smiley:

**Comment by lordofbikes** [comment]
I never used any AutoCAD software, so I can't say if `freeze` is the usual word for hiding layers.
Just through other free CAD software I was aware that `freeze` is the synonym for show/hide layers. But this software used an ice crystal icon for `freeze` property which makes the relation between word and icon more obvious, but not necessarily about its function.
I think that for the most LibreCAD user the show/hide wording is more intuitive and this also matches with the :eye: icon.
So I advocate to eliminate these 4 `freeze` occurrences in the manual.
It's just important for programmer to know that `freeze` means `hide` and this is already well documented in DXF references.

**Comment by lordofbikes** [comment]
As @GSStnb mentioned correct in [LibreCAD Issue #1434](https://github.com/LibreCAD/LibreCAD/issues/1434), `freeze` is used in context menus too. So changing source code has some drawbacks and we stay with `freeze` by now.

Anyhow we must adjust the manual, because `freeze` is used in the context of the padlock icon, for blocks and layers.
But it must be used in the context of the eye icon.
