### ISSUE TITLE
PDF has many pages with crappy layout

### ISSUE THREAD

**Issue by ghost** [LibreCAD/docs#25]
PDF - https://readthedocs.org/projects/librecad/downloads/pdf/latest/

- Table of Contents has only 1 entry;
- Objects (tables, images) exceed the bounds of pages;
- Images placed on top of tables;
- and much more issues.

**Comment by lordofbikes** [comment]
This documentation is work in progress.
Focus is on content yet, checked via HTML interface.
Validity of other formats will be checked then.
Anyhow, thanks for reporting.

**Comment by flywire** [comment]
Fairly sure it has something to do with the numerous layout errors/warnings when running #60

```
\appx\fonts.rst:15: WARNING: Inline substitution_reference start-string without end-string.
\guides\annotate.rst:153: WARNING: Content block expected for the "table" directive; none found.
\guides\drawingsetup.rst:64: WARNING: Undefined substitution referenced: "icon01".
\ref\draw-prefs.rst:122: WARNING: Content block expected for the "table" directive; none found.
\ref\menu.rst:214: WARNING: Substitution definition "icon12" empty or invalid.
\ref\menu.rst:221: WARNING: Substitution definition "icon15" empty or invalid.
\ref\menu.rst:222: WARNING: Substitution definition "icon16" empty or invalid.
\ref\menu.rst:223: WARNING: Substitution definition "icon17" empty or invalid.
\ref\menu.rst:245: WARNING: Substitution definition "icon25" empty or invalid.
\ref\menu.rst:246: WARNING: Substitution definition "icon26" empty or invalid.
\ref\menu.rst:280: WARNING: Substitution definition "icon38" empty or invalid.
\ref\menu.rst:281: WARNING: Substitution definition "icon39" empty or invalid.
\ref\menu.rst:282: WARNING: Substitution definition "icon40" empty or invalid.
\ref\toolbars.rst:137: WARNING: Substitution definition "icon00" empty or invalid.
\ref\widgets.rst:168: WARNING: Content block expected for the "table" directive; none found.
\appx\license-gpl.rst: WARNING: document isn't included in any toctree
\ref\fundamentals.rst:101: WARNING: undefined label: keyboard (if the link has no caption the label must precede a section header)
c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sphinx_rtd_theme\search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
| build succeeded, 17 warnings.
```
Some missing svg files:

\ref\menu.rst
Line 214 icon12 Recent Files
Line 221 icon15 Widget Options
Line 222 icon16 Device Options
Line 223 icon17 Reload Style Sheet
Line 245 icon25 Fullscreen
Line 246 icon26 Statusbar
Line 280 icon38 Divide ??
Line 281 icon39 Gear plugin ??
Line 282 icon40 ESRI Shapefile ??

Mostly missing for: Plugins, Widgets, Drawings, Help

**Comment by flywire** [comment]
https://github.com/LibreCAD/LibreCAD/archive/2.2.0-rc1.zip -> [lcpics.txt](https://github.com/LibreCAD/docs/files/4100623/lcpics.txt)

**Comment by flywire** [comment]
The real issue is bad formatting https://librecad.readthedocs.io/en/latest/guides/annotate.html#text figures before the table. Particularly affects rendering on a narrow device.

**Comment by GSStnb** [comment]
RtD has a minimum screen width (perhaps 800 or 1024 px - I don't have the reference handy). Further, there is no comparison between the html and epub / pdf formats.  There are issues with both them that are not present with the html.  As noted, content takes priority.  Further efforts with formatting to follow first for html and then for pdf & epub. Text wrapping around left/right images are a problem and the work around is doesn't handle some situations very well.  I have a partial fix that i hope to refine and implement. Tables caused some problems tòo, to varying degrees.

Warnings are just that, they have no affect on the rendering.  "Errors" will cause the process to fail.

**Comment by flywire** [comment]
Generally agree.
- RtD does work on narrow screens, perhaps much narrower than originally intended, but there are issues
- Warnings might not cause the process to fail but usually the intended functionality doesn't work

If tables can be displayed without vertical lines separating the columns it might look better in some formats.

**Comment by flywire** [comment]
> Text wrapping around left/right images are a problem

Agree. The 50 align clauses ([lcdocs-align-locations.txt](https://github.com/LibreCAD/docs/files/4124879/lcdocs-align-locations.txt): - 21 centre, 26 right, 3  left) demonstrate adopting align centre would eliminate most of the issues across different devices/screens/formats.

**Comment by GSStnb** [comment]
The problem might also be related to how the PDF/epub process handles scaled images, along with align. Or, it may be related to tables with images.  I'm going to put some effort into determining what the problem actually is.
I also have been considering alternative approaches to fixing the layout while retaining the current alignment.  The HTML version offers many advantages so it takes precedent over PDF / epub. 
 A reasonable PDF can be generated from the downloaded html.  
Centring all the images maybe the last resort.

**Comment by flywire** [comment]
> demonstrate adopting align centre

I put the [Layout](https://github.com/flywire/docs/tree/Layout) branch together to demonstrate it. Looks better in the interim till the layout issues are resolved.

**Comment by lordofbikes** [comment]
seems to be solved
