### ISSUE TITLE
Text Tools Table fix

### ISSUE THREAD

**Issue by GSStnb** [LibreCAD/docs#37]
Table below Text tool images does not appear on Dimn & Text guide (Assign to GSStnb)

**Comment by GSStnb** [comment]
Refer to PR "Fixed Text table #36"

**Comment by lordofbikes** [comment]
Gary, when you place the text "fix #??" in the commit message, github will close the referred issue automatically with the merge.
E.g. commit message "fix #37, Text Tools table issue" will have closed this issue when I merged PR #36.
