### ISSUE TITLE
Reference links

### ISSUE THREAD

**Issue by ghost** [LibreCAD/docs#48]
Is this book already listed in references list?

> https://twitter.com/eima_katalogoa/status/1151027522823475200

> Bi dimentsiotako marrazketa ordenagailu bidez (LibreCAD) [Interneteko baliabidea]: http://eimakatalogoa.eus/vufind/Record/47972
> 
> ![pic1](http://klasikoa.eimakatalogoa.eus/cgi-bin/koha/opac-image.pl?thumbnail=0&biblionumber=47972)

**Comment by GSStnb** [comment]
It is not in the RtD LibreCAD User Manual.  The best place for the link would be the wiki (https://wiki.librecad.org/index.php?title=LibreCAD_Manuals_Summary).  A brief description (in both languages) would be required and potentially permisson from the author (depending on the copyright).

**Comment by GSStnb** [comment]
It is not in the RtD User Manual, but could be added to the wiki (https://wiki.librecad.org/index.php?title=LibreCAD_Manuals_Summary).  A brief description (in both languages) would be required and potentially permisson from the author (depending on the copyright).

**Comment by GSStnb** [comment]
Add a link to the Appendices / Online Resource section of the RtD User Manual for "Manuals Summary" (https://wiki.librecad.org/index.php?title=LibreCAD_Manuals_Summary)

**Comment by ghost** [comment]
One more third-party user manual: *«LibreCAD for Real Dummies» (2019, WIP) by [Johnny Heikell](http://www.heikell.fi/downloads.htm)*

- http://www.heikell.fi/downloads/LibCAD_220rc1.pdf

![pic.1](https://i.imgur.com/rctfDg7.png)

**Comment by GSStnb** [comment]
Added to DokuWiki

**Comment by ghost** [comment]
Also, please, add links to backups on web archive.

To make backups of actually available PDFs:

- `https://web.archive.org/save/<URL-to-actually-available-PDF>`
