### ISSUE TITLE
Incorrect Links

### ISSUE THREAD

**Issue by tarrare2** [LibreCAD/docs#49]
https://librecad.readthedocs.io/en/latest/guides/blocks.html
Where it says "See Angles in LibreCAD" it goes to: https://librecad.readthedocs.io/en/latest/ref/fundamentals.html#fundamentals when it should but it reallyshould go to:
https://librecad.readthedocs.io/en/latest/ref/fundamentals.html#polar
or even
https://librecad.readthedocs.io/en/latest/ref/toolbars.html#from-block-list
Another thing I should ask is if the first two asterisks in the Layer List Dock section of https://librecad.readthedocs.io/en/latest/ref/widgets.html are doing what they are supposed to, as they go to 
https://librecad.readthedocs.io/en/latest/ref/widgets.html#id3 (for the first asterisk and id5 for the second) and the rest aren't connected to a link.
P.S. This is pasted from my GCI task, not the other way around 😄

**Comment by lordofbikes** [comment]
Great @Tarrare-the-Behemoth , many thanks again

**Comment by GSStnb** [comment]
Corrected with PR related to "issue49"
