### ISSUE TITLE
Missing shortcut for layer edit

### ISSUE THREAD

**Issue by fa201** [LibreCAD/docs#53]
To be added at https://librecad.readthedocs.io/en/latest/ref/widgets.html#layer-list-dock
CTRL+L only for active layer.

**Comment by fa201** [comment]
To be added layer: small bug on the status of layer when using this short-cut;
See [issue #1182](https://github.com/LibreCAD/LibreCAD/issues/1182)

**Comment by GSStnb** [comment]
The shortcut should be added, but [Crtl]+[L] adds a layer with the same name as the currently selected layer plus an increment number (1, 2, ...).  If "myLayer" is the current layer, pressing [Crtl]+[L] will add a new layer "myLayer1".

**Comment by fa201** [comment]
Thanks for the clarification. Then I close the issue...

**Comment by fa201** [comment]
Implemented in PR #58
