### ISSUE TITLE
Image Presentation

### ISSUE THREAD

**Issue by flywire** [LibreCAD/docs#63]
More consistent [image sizes](https://github.com/LibreCAD/docs/files/4142248/ImageSizes.csv.txt) would improve appearance. Some sizes are fixed in code but even there they should be consistent sizes.

Preferable to adopt regular sizes, say 300x250px. Using existing 291px wide images with 250px length as an example:

![dock-penWizard00](https://user-images.githubusercontent.com/11288701/73591653-63f0b200-4545-11ea-987b-aa75ef04a6ef.png)

![dock-blockList00](https://user-images.githubusercontent.com/11288701/73591779-3442a980-4547-11ea-93b0-d44c6cf0df4e.png)

![dock-layerList00](https://user-images.githubusercontent.com/11288701/73591840-d82c5500-4547-11ea-9819-22be5a33987e.png)

**Comment by GSStnb** [comment]
Image sizes, particularly for dialog boxes, are the default sizes taken from LC with a default installation.  Some adjustment is suitable for dialog boxes that are docked in the same space on screen, but not for others located elsewhere.
Retaining the default sizes will match, or be consistent with, the sizes as they would appear to a new user.

**Comment by flywire** [comment]
Older images are simpler and clearer than current ones, especially when tested in User Manual where they are scaled down. Differences include white background, larger bolder text and lines, consistently plainer font, and only demonstrates key point.

eg Angles in LibreCAD - old above and current below:

![Selection_030](https://user-images.githubusercontent.com/11288701/73592370-a28a6a80-454d-11ea-9faf-ab28dc624570.png)

![angles](https://user-images.githubusercontent.com/11288701/73592356-7e2e8e00-454d-11ea-8b5f-64fbb04ebd7d.png)

**Comment by flywire** [comment]
@GSStnb
* [image sizes](https://github.com/LibreCAD/docs/files/4142248/ImageSizes.csv.txt) file demonstrates they are not all default sizes
* agree some sizes from code seem fairly random
* gui layout changes with display resolution, screenshots from the [most common desktop display resolution in 2019](https://www.hobo-web.co.uk/best-screen-size) (1366×768) _might_ be better for user documentation
* gui layout is not necessarily the best to communicate information in a user manual
* excessive white space takes focus off point being communicated

![image](https://user-images.githubusercontent.com/11288701/73603243-6ea65800-45d4-11ea-8123-cac7edc3b576.png)
Default LibreCAD 2.2.0-rc1 install on 1366×768 display

**Comment by GSStnb** [comment]
Place holder draft images were updated in revision.
