### ISSUE TITLE
First Page Unavailable from TOC

### ISSUE THREAD

**Issue by flywire** [LibreCAD/docs#64]
[First page](https://librecad.readthedocs.io/en/latest/index.html)  unavailable from TOC. Consider combining with [About](https://librecad.readthedocs.io/en/latest/about/index.html) .

**Comment by GSStnb** [comment]
Not required. Clicking "LibreCAD" or the icon at the top of the menu will return you to the home page from anywhere in the manual

**Comment by flywire** [comment]
Tested a small screen?

**Comment by GSStnb** [comment]
Yes

**Comment by flywire** [comment]
Hmm, 640x960

![image](https://user-images.githubusercontent.com/11288701/73704737-23ad5180-4748-11ea-8823-68222af79a1f.png)
