### ISSUE TITLE
Printing Guide Complicated by Scale Issue

### ISSUE THREAD

**Issue by flywire** [LibreCAD/docs#72]
Three of the 5 print sections are about scale:

* Put scale topics as subheadings under scale
* Border and Title Blocks complicate guide section and are out of place - move to a different part of User Manual or a tutorial
* Rationalise `assume the drawing to be printed was drawn full-scale (1:1)`. It is a critical point so perhaps make first step under each scale subheading.

> Printing

> * Printing, Quick and Easy
> * Scale
>     - Printing to Scale
>     - Printing to Scale with Dimensions
>     - Printing to Scale ~~with a Border and Title Block~~
> * Tiled Printing

I'm happy to submit as PR if change accepted.

**Comment by GSStnb** [comment]
N/A as the section was re-written.
Adding a border and title block is a common practise and is appropriate for the guide.
Drawing full scale identified numerous locations.

**Comment by flywire** [comment]
re-written section is confusing for printing
