### ISSUE TITLE
Annotating and Dimensioning Circles and Arcs

### ISSUE THREAD

**Issue by flywire** [LibreCAD/docs#85]
Review unique issues with annotating and dimensioning circles and arcs in the [Annotation Guide](https://github.com/LibreCAD/docs/blob/master/guides/annotate.rst):

1. Consistent center lines/marks
1. Label radius/diameter internal/external at angle

Examples:
1. [Multiple circles through the same centre-point](https://forum.librecad.org/file/n5717860/diameters.png) - see https://heikell.fi/downloads/LibCAD_220rc1.pdf Exercise 5 p73
1. https://forum.librecad.org/file/n5718399/Bracket_dell.pdf - Side View: hole diameter, top arc diameter; End View: inner and outer radius

**Comment by GSStnb** [comment]
Dimensioning is a drafting topic and a comprehensive guide is out of scope for the User Manual.  There are many resources available on the web.  Search for "drafting dimensioning".
