### ISSUE TITLE
Some tables are too large for the page setup

### ISSUE THREAD

**Issue by fa201** [LibreCAD/docs#9]
See example below : 
![table](https://user-images.githubusercontent.com/49532187/56093592-fd71a900-5eca-11e9-9f7e-f31fbe1176c3.png)
Could we enlarge this page setup to avoid this big slider or least reduce it ?
Note that the table in the PDF is formatted OK.

**Comment by lordofbikes** [comment]
This is a known issue with _Read the docs / Sphinx_, see https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
@GSStnb has fixed this recently, but the fix needs an additional file, which will be added soon.

**Comment by fa201** [comment]
OK. Then I close the issue ?

**Comment by lordofbikes** [comment]
Fixed with latest merge #13
