### ISSUE TITLE
Dimension property: text is also supported

### ISSUE THREAD

**Issue by fa201** [LibreCAD/docs#99]
**Although it may not be a good practice**, LibreCAD supports dimension editing to add text in place of dimenion. For example, if one needs to show the actual stroke of a lever then instead of showing "100 mm" one can show "Lever stroke: 100 mm" in the dimension text.

Additional information could be located and cross-linked at :
https://librecad.readthedocs.io/en/latest/guides/dwg-edit.html#changing-attributes-and-properties
https://librecad.readthedocs.io/en/latest/guides/annotate.html#dimensioning-appearance

**Comment by lordofbikes** [comment]
It seems, that using `<>` as placeholder in dimension text is also not documented yet.
See https://forum.librecad.org/displaying-an-original-dimension-plus-an-additional-text-tp5721869.html
